# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "MovieSearch")
    crashlytics(api_token: "34825100e96323365d3bd98baa92c47125b61281",
              build_secret: "9bb92196a08d3fbf4c36b695e18fdb05ccfa0d28fe29fe3785be5c9d43819af6")
  end
end


lane :screenshots do
  capture_screenshots
  upload_to_app_store
end
